In [13]:
from plantillasArquitectura import Datos as d
from scipy.stats import norm

import numpy as np
lenses = d.Datos('./plantillasArquitectura/datos/conjunto_datos_lentillas.txt')
lenses.datos
datosTrain=lenses.datos
atributosDiscretos = lenses.nominalAtributos
print(lenses.nombreAtributos)
print(lenses.tipoAtributos)
print(lenses.nominalAtributos)
print(lenses.diccionarios)
print(lenses.datos)

['Age', 'Spectacle', 'Astigmatic', 'Tear', 'Class']
['Nominal', 'Nominal', 'Nominal', 'Nominal', 'Nominal']
[True, True, True, True, True]
[{'1': 0, '2': 1, '3': 2}, {'1': 0, '2': 1}, {'1': 0, '2': 1}, {'1': 0, '2': 1}, {'1': 0, '2': 1, '3': 2}]
[[0. 0. 0. 0. 2.]
 [0. 0. 0. 1. 1.]
 [0. 0. 1. 0. 2.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 2.]
 [0. 1. 0. 1. 1.]
 [0. 1. 1. 0. 2.]
 [0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 1. 1.]
 [1. 0. 1. 0. 2.]
 [1. 0. 1. 1. 0.]
 [1. 1. 0. 0. 2.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 2.]
 [1. 1. 1. 1. 2.]
 [2. 0. 0. 0. 2.]
 [2. 0. 0. 1. 2.]
 [2. 0. 1. 0. 2.]
 [2. 0. 1. 1. 0.]
 [2. 1. 0. 0. 2.]
 [2. 1. 0. 1. 1.]
 [2. 1. 1. 0. 2.]
 [2. 1. 1. 1. 2.]]


In [14]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/conjunto_datos_lentillas.txt')
estrategia = ep.ValidacionSimple(25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.16666666666666666

In [15]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/conjunto_datos_lentillas.txt')
estrategia = ep.ValidacionCruzada(5)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.25

In [16]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/tic-tac-toe.data')
estrategia = ep.ValidacionSimple( 25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.26778242677824265

In [17]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/tic-tac-toe.data')
estrategia = ep.ValidacionCruzada( 10)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.30526315789473685

In [20]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/german.data')
estrategia = ep.ValidacionSimple(25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.26

In [19]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/german.data')
estrategia = ep.ValidacionCruzada(17)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.2505070993914807