In [1]:
from plantillasArquitectura import Datos as d
from scipy.stats import norm

import numpy as np
lenses = d.Datos('./plantillasArquitectura/datos/conjunto_datos_lentillas.txt')
lenses.datos
datosTrain=lenses.datos
atributosDiscretos = lenses.nominalAtributos
print(lenses.nombreAtributos)
print(lenses.tipoAtributos)
print(lenses.nominalAtributos)
print(lenses.diccionarios)
print(lenses.datos)

['Age', 'Spectacle', 'Astigmatic', 'Tear', 'Class']
['Nominal', 'Nominal', 'Nominal', 'Nominal', 'Nominal']
[True, True, True, True, True]
[{'1': 0, '2': 1, '3': 2}, {'1': 0, '2': 1}, {'1': 0, '2': 1}, {'1': 0, '2': 1}, {'1': 0, '2': 1, '3': 2}]
[[0. 0. 0. 0. 2.]
 [0. 0. 0. 1. 1.]
 [0. 0. 1. 0. 2.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 2.]
 [0. 1. 0. 1. 1.]
 [0. 1. 1. 0. 2.]
 [0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 1. 1.]
 [1. 0. 1. 0. 2.]
 [1. 0. 1. 1. 0.]
 [1. 1. 0. 0. 2.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 2.]
 [1. 1. 1. 1. 2.]
 [2. 0. 0. 0. 2.]
 [2. 0. 0. 1. 2.]
 [2. 0. 1. 0. 2.]
 [2. 0. 1. 1. 0.]
 [2. 1. 0. 0. 2.]
 [2. 1. 0. 1. 1.]
 [2. 1. 1. 0. 2.]
 [2. 1. 1. 1. 2.]]


In [2]:
print(lenses.diccionarios[-1])
a = []
b =[9,9,9,9,9,9,9]
i = 0
for key in lenses.diccionarios[-1]:
    print(key)
    a.append(key)
    b[i]=key
    i+=1
print(lenses.diccionarios[-1].keys())
print(a)
print(b)

{'1': 0, '2': 1, '3': 2}
1
2
3
dict_keys(['1', '2', '3'])
['1', '2', '3']
['1', '2', '3', 9, 9, 9, 9]


In [3]:
print(datosTrain.shape)
print(type(datosTrain))
prioris = dict()
nDatos = len(datosTrain)
classIdx = np.size(datosTrain,1)-1 
for dato in datosTrain:
    clase = dato[classIdx]
    if clase not in prioris.keys():
        prioris[clase] = 1/nDatos
    else :
        prioris[clase] += 1/nDatos
classes = list((datosTrain[:, -1]))
third = list(set(datosTrain[:, 2]))

filteredColumn = datosTrain[datosTrain[:,-1]==classes[0]][:,3]
print(filteredColumn)
mean = np.mean(filteredColumn)
std = np.std(filteredColumn)
gen = norm(mean, std)
print(gen.pdf(0.5))                
np.sum((datosTrain[:,2]==third[0] ) & (datosTrain[:,-1]==classes[0]))

(24, 5)
<class 'numpy.ndarray'>
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1.]
0.752843580387011


7

In [4]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/conjunto_datos_lentillas.txt')
estrategia = ep.ValidacionSimple('Nombre de estrategia', 25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)

In [5]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/german.data')
estrategia = ep.ValidacionSimple('Nombre de estrategia', 25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)

clase  0 atributo num 1
[45.]
[[42.  2.]
 [48.  1.]
 [11.  1.]
 ...
 [36.  2.]
 [26.  1.]
 [21.  1.]]
clase  0 atributo num 4
[4576.]
[[3.965e+03 2.000e+00]
 [7.476e+03 1.000e+00]
 [4.771e+03 1.000e+00]
 ...
 [8.229e+03 2.000e+00]
 [7.966e+03 1.000e+00]
 [2.993e+03 1.000e+00]]
clase  0 atributo num 7
[3.]
[[4. 2.]
 [4. 1.]
 [2. 1.]
 ...
 [2. 2.]
 [2. 1.]
 [3. 1.]]
clase  0 atributo num 10
[4.]
[[3. 2.]
 [1. 1.]
 [4. 1.]
 ...
 [2. 2.]
 [3. 1.]
 [2. 1.]]
clase  0 atributo num 12
[27.]
[[34.  2.]
 [50.  1.]
 [51.  1.]
 ...
 [26.  2.]
 [30.  1.]
 [28.  1.]]
clase  0 atributo num 15
[1.]
[[1. 2.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 2.]
 [2. 1.]
 [2. 1.]]
clase  0 atributo num 17
[1.]
[[1. 2.]
 [1. 1.]
 [1. 1.]
 ...
 [2. 2.]
 [1. 1.]
 [1. 1.]]


/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:1720: RuntimeWarning: divide by zero encountered in double_scalars
  x = np.asarray((x - loc)/scale, dtype=dtyp)
/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:1720: RuntimeWarning: invalid value encountered in double_scalars
  x = np.asarray((x - loc)/scale, dtype=dtyp)


In [13]:
np.set_printoptions(suppress=True)
for i in range(10):
    print(dataset.datos[i])
print(dataset.datos[-10:])


[   0.    6.    4.    4. 1169.    4.    4.    4.    2.    0.    4.    0.
   67.    2.    1.    2.    2.    1.    1.    0.    1.]
[   1.   48.    2.    4. 5951.    0.    2.    2.    1.    0.    2.    0.
   22.    2.    1.    1.    2.    1.    0.    0.    2.]
[   3.   12.    4.    7. 2096.    0.    3.    2.    2.    0.    3.    0.
   49.    2.    1.    1.    1.    2.    0.    0.    1.]
[   0.   42.    2.    3. 7882.    0.    3.    2.    2.    2.    4.    1.
   45.    2.    2.    1.    2.    2.    0.    0.    1.]
[   0.   24.    3.    0. 4870.    0.    2.    3.    2.    0.    4.    3.
   53.    2.    2.    2.    2.    2.    0.    0.    2.]
[   3.   36.    2.    7. 9055.    4.    2.    2.    2.    0.    4.    3.
   35.    2.    2.    1.    1.    2.    1.    0.    1.]
[   3.   24.    2.    3. 2835.    2.    4.    3.    2.    0.    4.    1.
   53.    2.    1.    1.    2.    1.    0.    0.    1.]
[   1.   36.    2.    1. 6948.    0.    2.    2.    2.    0.    2.    2.
   35.    2.    0.    1.

In [14]:
print(dataset.datos)

[[ 0.  6.  4. ...  1.  0.  1.]
 [ 1. 48.  2. ...  0.  0.  2.]
 [ 3. 12.  4. ...  0.  0.  1.]
 ...
 [ 3. 12.  2. ...  0.  0.  1.]
 [ 0. 45.  2. ...  1.  0.  2.]
 [ 1. 45.  4. ...  0.  0.  0.]]
