In [13]:
from plantillasArquitectura import Datos as d
from scipy.stats import norm

import numpy as np
lenses = d.Datos('./plantillasArquitectura/datos/conjunto_datos_lentillas.txt')
lenses.datos
datosTrain=lenses.datos
atributosDiscretos = lenses.nominalAtributos
print(lenses.nombreAtributos)
print(lenses.tipoAtributos)
print(lenses.nominalAtributos)
print(lenses.diccionarios)
print(lenses.datos)

['Age', 'Spectacle', 'Astigmatic', 'Tear', 'Class']
['Nominal', 'Nominal', 'Nominal', 'Nominal', 'Nominal']
[True, True, True, True, True]
[{'1': 0, '2': 1, '3': 2}, {'1': 0, '2': 1}, {'1': 0, '2': 1}, {'1': 0, '2': 1}, {'1': 0, '2': 1, '3': 2}]
[[0. 0. 0. 0. 2.]
 [0. 0. 0. 1. 1.]
 [0. 0. 1. 0. 2.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 2.]
 [0. 1. 0. 1. 1.]
 [0. 1. 1. 0. 2.]
 [0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 1. 1.]
 [1. 0. 1. 0. 2.]
 [1. 0. 1. 1. 0.]
 [1. 1. 0. 0. 2.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 2.]
 [1. 1. 1. 1. 2.]
 [2. 0. 0. 0. 2.]
 [2. 0. 0. 1. 2.]
 [2. 0. 1. 0. 2.]
 [2. 0. 1. 1. 0.]
 [2. 1. 0. 0. 2.]
 [2. 1. 0. 1. 1.]
 [2. 1. 1. 0. 2.]
 [2. 1. 1. 1. 2.]]


In [1]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/conjunto_datos_lentillas.txt')
estrategia = ep.ValidacionSimple(25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.16666666666666666

In [2]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/conjunto_datos_lentillas.txt')
estrategia = ep.ValidacionCruzada(5)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.25

In [3]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/tic-tac-toe.data')
estrategia = ep.ValidacionSimple( 25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.32217573221757323

In [4]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/tic-tac-toe.data')
estrategia = ep.ValidacionCruzada( 10)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.2989473684210527

In [5]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/german.data')
estrategia = ep.ValidacionSimple(25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.236

In [6]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/german.data')
estrategia = ep.ValidacionCruzada(17)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador)
errores

0.24847870182555784

In [8]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/conjunto_datos_lentillas.txt')
estrategia = ep.ValidacionSimple(25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador, laplace = True)
errores

0.16666666666666666

In [2]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/conjunto_datos_lentillas.txt')
estrategia = ep.ValidacionCruzada(5)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador, laplace = True)
errores

0.25

In [3]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/tic-tac-toe.data')
estrategia = ep.ValidacionSimple( 25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador, laplace = True)
errores

0.301255230125523

In [4]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/tic-tac-toe.data')
estrategia = ep.ValidacionCruzada(10)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador, laplace = True)
errores

0.3042105263157895

In [5]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/german.data')
estrategia = ep.ValidacionSimple(25)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador, laplace = True)
errores

0.216

In [6]:
from plantillasArquitectura import Clasificador as cl
from plantillasArquitectura import EstrategiaParticionado as ep
from plantillasArquitectura import Datos as d

dataset = d.Datos('./plantillasArquitectura/datos/german.data')
estrategia = ep.ValidacionCruzada(7)
clasificador = cl.ClasificadorNaiveBayes()
errores = clasificador.validacion(estrategia,dataset,clasificador, laplace = True)
errores

0.24849094567404428